name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "learning lab user"
          second-greeting: "hank simpleton"
          third-greeting: "lyra simpfield"
