name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "learning lab user"
          second-greeting: "hank simpleton"
          third-greeting: "lyra simpfield"

      - name: ha-ha
        uses: ./.github/actions/joke-action
      
      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}